### ISSUE TITLE
讨论：DragLike 下面用 children 属性 来接收卡片（让卡片数量不再是固定的两张），类似多米诺骨牌、纸牌接龙的层叠视觉效果

### ISSUE THREAD

**Issue by DoodleBears** [ihongwu/DragLike#4]
# 可能可以新增的功能（近期应该会开始写，想讨论下）
1. DragLike 下面用 **children 属性** 来接收卡片（让卡片数量不再是固定的两张）
   - 通过设置 **itemCount 属性** 来控制渲染数量
   - 允许设置每层的 **scale 比例** —— 如：面前的Scale = 1，然后 0.9，0.8 ... 0.5 （可以到某一个数量时维持不变）
   - 允许设置每层的 **offset 量**（通过设置 offset 和 scale 就会有类似多米诺骨牌、纸牌接龙的层叠视觉效果）
2. DragLike 增加 **controller 属性** 方便通过Button等其他方式**触发划卡动作**

**Comment by ihongwu** [comment]
@DoodleBears 
### 感谢对该插件的持续关注！
第一个建议可以定义枚举类型设置：是设置固定两个**child**，还是使用**children**，两个的实现方式以及数据的刷新可能大不同
第二个增加**controller**，通过controller触发动作是必须的，建议提高优先级


**Notice: 当前已使用ValueNotifier来刷新，您在升级过程中也应避免使用setstate**


### Thanks!

**Comment by DoodleBears** [comment]
## **感谢回应**
### 1. 关于第一个建议
是指用枚举区分
 - 有限个 (2个) 情况下一种渲染机制
 - children 另一种渲染机制？

### 2. 关于数据刷新的不同
是指像2个children情况下，在isCompleted 之后，在list中回收remove掉划出item嘛？想请问具体是指什么数据刷新）

### 3. 关于增加 controller
了解了，没有写过类似的方案，届时会参考Flutter的源码，但感觉上不会特别复杂？自己认为主要是注入controller，调用draglike内部的function

---

关于用 **ValueNotifier** 来刷新已经在源码中看到了，感谢您后来优化的代码（愿意merge我的PR，看了你写的之后，才知道原来能那么简洁高效的解决）

**Comment by ihongwu** [comment]
### 第一个说明：
改成children，由于跟目前的效果区分比较大，改成children势必会增加多层动画，性能会有一定的影响，跟当前的动画效果大部分判断逻辑都不一样，所以建议分离：保留当前的，新增children渲染

### 第二个说明
数据刷新时机应该由调用层决定，插件不刷新数据，插件刷新主要指的是动画刷新

### 第三个说明：
第三个我抽时间增加下controller

**Comment by ihongwu** [comment]
### @DoodleBears 
**drag_like 2.1.0**  已增加 controller 属性，方便通过Button等其他方式触发划卡动作


**类似多米诺骨牌、纸牌接龙的层叠视觉效果，期待你贡献代码！**
