### ISSUE TITLE
支持拖动任意位置显示出来效果吗 

### ISSUE THREAD

**Issue by libaipeng1314** [ihongwu/DragLike#5]

**Comment by ihongwu** [comment]
我不是很明白你的意思

**Comment by libaipeng1314** [comment]
类似附件的效果


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ihongwu/DragLike"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ihongwu/DragLike] 支持拖动任意位置显示出来效果吗  (Issue #5)





 
我不是很明白你的意思
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ihongwu** [comment]
抱歉，好像没有附件，如果可以，你可以将附件上传到GitHub

**Comment by libaipeng1314** [comment]
如下可以自由拖动吗
![WechatIMG412](
https://user-images.githubusercontent.com/49401629/143548615-c06a3b16-4e51-4b19-b702-4665f352d493.mp4
)

**Comment by libaipeng1314** [comment]
已经更新了 谢谢
https://user-images.githubusercontent.com/49401629/143548493-6f8db841-853d-422d-a801-095cc2ebfd7a.jpeg


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ihongwu/DragLike"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ihongwu/DragLike] 支持拖动任意位置显示出来效果吗  (Issue #5)





 
抱歉，好像没有附件，如果可以，你可以将附件上传到GitHub
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ihongwu** [comment]
目前还不支持的

**Comment by libaipeng1314** [comment]
后期会支持吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ihongwu/DragLike"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ihongwu/DragLike] 支持拖动任意位置显示出来效果吗  (Issue #5)





 
目前还不支持的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ihongwu** [comment]
短时间内没有计划，如果急切，可以查阅其他插件

**Comment by libaipeng1314** [comment]
有其它类似的插件吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ihongwu/DragLike"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ihongwu/DragLike] 支持拖动任意位置显示出来效果吗  (Issue #5)





 
短时间内没有计划，如果急切，可以查阅其他插件
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ihongwu** [comment]
不是很清楚，你可以搜索搜索查找一下，看看有没有

**Comment by libaipeng1314** [comment]
拖动的时候 可以判断是右滑还是左滑吗

**Comment by libaipeng1314** [comment]
你好的 左右滑动中 可以通过什么判断 是左滑还是右滑吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ihongwu/DragLike"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ihongwu/DragLike] 支持拖动任意位置显示出来效果吗  (Issue #5)





 
不是很清楚，你可以搜索搜索查找一下，看看有没有
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ihongwu** [comment]
onChangeDragDistance回调，Map下标的distance，小于0代表左滑，大于0代表右滑

**Comment by ihongwu** [comment]
![image](https://user-images.githubusercontent.com/21274377/143983422-a06a84f9-e240-4549-83fb-5d8f0ecb02d1.png)
